version: '3.4'

services:
  customers:
    image: gleniox/ecommerceapicustomers:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  orders:
    image: gleniox/ecommerceapiorders:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  products:
    image: gleniox/ecommerceapiproducts:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  search:
    image: gleniox/ecommerceapisearch:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://10.0.0.4:19081/lil/products 
      - Services__Customers=http://10.0.0.4:19081/lil/customers
      - Services__Orders=http://10.0.0.4:19081/lil/orders
    ports:
      - "6004:80"

